services:
  bot:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://postgres:123@pg/blackjack
    depends_on:
      pg:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./bot-logs/:/app/bot-logs

  pg:
    image: postgres:17.4
    environment:
      POSTGRES_DB: blackjack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - black_jack_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  black_jack_pg_data: